### ISSUE TITLE
Please Consider adding a permissive license to this repository

### ISSUE THREAD

**Issue by AsheKR** [karol-brejna-i/docker-locust#14]
I am interested in this library. I would like to use your scripts and Dockerfile as an example/base for custom scripts but this is currently not possible. Please add an appropriate LICENSE file to the repository.

**Comment by karol-brejna-i** [comment]
@AsheKR Can you confirm the solution works for you?

**Comment by venkat566** [comment]
@karol-brejna-i  - Do we have the latest locust image that we can download ?
Looks like this was last updated 3 years ago. Need help with this

**Comment by karol-brejna-i** [comment]
@venkat566 Many things improved in Locust since this Docker image was created. There is an official image available out there: https://docs.locust.io/en/stable/running-in-docker.html

If you are interested in using `karol-brejna-i/docker-locust` image, I can update it in the following days. Let me know.

**Comment by venkat566** [comment]
@karol-brejna-i 
It would really help if you can update the image.
Your image was quite easy to pull and add dependencies on top of it. 
if its possible please update the image soon possible. We need standalone image option which I can pass as environment variable 

thank you for response on this
